database:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - /opt/mongodb:/data/db

application:
  image: mrichard/weddingapp:3
  ports:
    - "8080:8080"
  links:
    - database
  volumes:
    - ./server/server.js:/usr/src/app/server/server.js
